#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MapSuiteSiteSelection.Resource", IsApplication=true)]

namespace MapSuiteSiteSelection
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::MapSuiteSiteSelection.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::MapSuiteSiteSelection.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int basemap = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int clear = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int Compass = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int displaytype_bing_aerial = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int displaytype_bing_road = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int displaytype_osm = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int displaytype_wmk = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int drawPoint = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int DrugStore = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int FilterByArea = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int FilterByType = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int find = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int Hotel = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int Icon = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int icon_mapsuite_default256x256 = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int icon_mapsuite_default512x512 = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int icon_mapsuite_globe = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int icon_mapsuite_globe_Pressed = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int icon_mapsuite_Minus = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int icon_mapsuite_Minus_Pressed = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int icon_mapsuite_noImageTile = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int icon_mapsuite_Plus = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int icon_mapsuite_Plus_Pressed = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int linearlayoutStyle = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int MapSuite = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int pan = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int public_facility = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int restaurant = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int sampleIcon = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int school = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int searchicon = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int selectedHalo = 2130771999;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F02000A
			public const int bingaRadioButton = 2130837514;
			
			// aapt resource value: 0x7F020000
			public const int BingMapsKeyEditText = 2130837504;
			
			// aapt resource value: 0x7F02000B
			public const int bingrRadioButton = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int bufferAreaRadioButton = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int bufferLineBreakLayout = 2130837517;
			
			// aapt resource value: 0x7F020001
			public const int CancelButton = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ClearButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ColumnTypeSpinner = 2130837507;
			
			// aapt resource value: 0x7F02000E
			public const int distanceUnitSpinner = 2130837518;
			
			// aapt resource value: 0x7F020004
			public const int DrawPointButton = 2130837508;
			
			// aapt resource value: 0x7F02000F
			public const int editBufferValueText = 2130837519;
			
			// aapt resource value: 0x7F020005
			public const int FeatureLayerTypeSpinner = 2130837509;
			
			// aapt resource value: 0x7F020010
			public const int iconView = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int listView = 2130837521;
			
			// aapt resource value: 0x7F020006
			public const int MapContainer = 2130837510;
			
			// aapt resource value: 0x7F020012
			public const int nameView = 2130837522;
			
			// aapt resource value: 0x7F020007
			public const int OkButton = 2130837511;
			
			// aapt resource value: 0x7F020013
			public const int osmRadioButton = 2130837523;
			
			// aapt resource value: 0x7F020008
			public const int PanButton = 2130837512;
			
			// aapt resource value: 0x7F020014
			public const int radioGroup1 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int searchButton = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int similarSiteTitleTextView = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int textView1 = 2130837527;
			
			// aapt resource value: 0x7F020009
			public const int ToolsLinearLayout = 2130837513;
			
			// aapt resource value: 0x7F020018
			public const int uploadDataTextView = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int uploadProgressBar = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int wmkAerialRadioButton = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int wmkAerialWithLabelsRadioButton = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int wmkRoadRadioButton = 2130837532;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int BingMapsKeyLayout = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int FilterByAreaDialogLayout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int FilterByTypeDialogLayout = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int ListItemTemplate = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int PotentialSimilarSitesLayout = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int RadioButtonTextColorSelector = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int RadioButtonTextSizeSelector = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int SelectBaseMapTypeLayout = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int SpinnerTextViewLayout = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int SplashLayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int BufferDistance = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Clear = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Hello = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int MinutesDriving = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int Option = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int Pan = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int Pin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ServiceAreaIn = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int TypeText = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int ZoomTo = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
