#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MapSuiteSiteSelection.Resource", IsApplication=true)]

namespace MapSuiteSiteSelection
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::MapSuiteSiteSelection.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::MapSuiteSiteSelection.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::MapSuiteSiteSelection.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int basemap = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clear = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Compass = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int displaytype_bing_aerial = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int displaytype_bing_road = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int displaytype_osm = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int displaytype_wmk = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int drawPoint = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DrugStore = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int FilterByArea = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int FilterByType = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int find = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Hotel = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_default256x256 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_mapsuite_default512x512 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_mapsuite_globe = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_mapsuite_globe_Pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_mapsuite_Minus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_mapsuite_Minus_Pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon_mapsuite_noImageTile = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon_mapsuite_Plus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int icon_mapsuite_Plus_Pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int linearlayoutStyle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int MapSuite = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pan = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int public_facility = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int restaurant = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int sampleIcon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int school = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int searchicon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int selectedHalo = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int BingMapsKeyEditText = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int CancelButton = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int ClearButton = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int ColumnTypeSpinner = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int DrawPointButton = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int FeatureLayerTypeSpinner = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int MapContainer = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int OkButton = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int PanButton = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int ToolsLinearLayout = 2131034125;
			
			// aapt resource value: 0x7f050019
			public const int bingaRadioButton = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int bingrRadioButton = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int bufferAreaRadioButton = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int bufferLineBreakLayout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int distanceUnitSpinner = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int editBufferValueText = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int iconView = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int listView = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int nameView = 2131034123;
			
			// aapt resource value: 0x7f050018
			public const int osmRadioButton = 2131034136;
			
			// aapt resource value: 0x7f05000e
			public const int radioGroup1 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int searchButton = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int similarSiteTitleTextView = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05001c
			public const int uploadDataTextView = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int uploadProgressBar = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int wmkAerialRadioButton = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int wmkAerialWithLabelsRadioButton = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int wmkRoadRadioButton = 2131034133;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BingMapsKeyLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FilterByAreaDialogLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FilterByTypeDialogLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItemTemplate = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PotentialSimilarSitesLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RadioButtonTextColorSelector = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RadioButtonTextSizeSelector = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SelectBaseMapTypeLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SpinnerTextViewLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SplashLayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int BufferDistance = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int Clear = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int MinutesDriving = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int Option = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int Pan = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int Pin = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int ServiceAreaIn = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int TypeText = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int ZoomTo = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
