#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GettingStartedSample.Resource", IsApplication=true)]

namespace GettingStartedSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::GettingStartedSample.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::GettingStartedSample.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::GettingStartedSample.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int location_scale_big = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int location_scale_small = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int toolsBar_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int toolsBar_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Compass = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int displaytype_bing_aerial = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int displaytype_wmk = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fullext40X40 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_mapsuite_default256x256 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_mapsuite_default512x512 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_mapsuite_globe = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_mapsuite_globe_Pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_mapsuite_Minus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_mapsuite_Minus_Pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_mapsuite_noImageTile = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_mapsuite_Plus = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_Plus_Pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int info40X40 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int location40X40 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MapSuite = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int mapType = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int More = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Nxtext40X40 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int portrait = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Preext40X40 = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int CancelButton = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int MapContainer = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int OkButton = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int ToolButtonsLayout = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int ToolsBarBorderFrameLayout = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int ToolsBarHeaderLayout = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int ToolsBarLinearLayout = 2131165185;
			
			// aapt resource value: 0x7f070018
			public const int ZoomLevelTextView = 2131165208;
			
			// aapt resource value: 0x7f07000d
			public const int baseMapButton = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int closeButton = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int cloudMapAerialRadioButton = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int cloudMapHybridRadioButton = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int cloudMapLightRadioButton = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int frameLayout1 = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int fullextImageButton = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int infoImageButton = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int landscapeTextView = 2131165191;
			
			// aapt resource value: 0x7f070017
			public const int localWebView = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int locationImageButton = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int moreImage = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int nxtextImageButton = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int preextImageButton = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int radioGroup1 = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int textView1 = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int zoomLevelListView = 2131165206;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBackgroundSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int OpenGpsSettingsLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SelectBaseMapTypeLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SelectZoomLevelLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ToolsBarTitleBackground = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WebView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ZoomLevelListTemplate = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
