#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RoutingSample.Resource", IsApplication=true)]

namespace RoutingSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Mono.Data.Sqlite.Resource.String.ApplicationName = global::RoutingSample.Resource.String.ApplicationName;
			global::Mono.Data.Sqlite.Resource.String.Hello = global::RoutingSample.Resource.String.Hello;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::RoutingSample.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::RoutingSample.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::RoutingSample.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::RoutingSample.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.Compass = global::RoutingSample.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_default256x256 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_default512x512 = global::RoutingSample.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_globe = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_globe_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_Minus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_noImageTile = global::RoutingSample.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_Plus = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Layers.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::RoutingSample.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Layers.Resource.String.ApplicationName = global::RoutingSample.Resource.String.ApplicationName;
			global::ThinkGeo.MapSuite.Layers.Resource.String.Hello = global::RoutingSample.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Compass = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_mapsuite_default256x256 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_mapsuite_default512x512 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_mapsuite_globe = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_mapsuite_globe_Pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_mapsuite_Minus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_mapsuite_Minus_Pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_mapsuite_noImageTile = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_mapsuite_Plus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_mapsuite_Plus_Pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int MapSuite = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int DirectionListView = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int DirectionView = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int LengthView = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int ListViewHeader = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int MapContainerView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int RoadNameView = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int uploadDataTextView = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int uploadProgressBar = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SplashLayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
