#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnalyzingVisualization.Resource", IsApplication=true)]

namespace AnalyzingVisualization
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::AnalyzingVisualization.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::AnalyzingVisualization.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::AnalyzingVisualization.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int bottomViewIn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bottomViewOut = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int classbreak = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int clusterstyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Compass = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int customstyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int detail40 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dotdensity = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int filterstyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int graySettings40 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int heatmap = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_mapsuite_default256x256 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_mapsuite_default512x512 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_mapsuite_globe = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_mapsuite_globe_Pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_Minus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_mapsuite_Minus_Pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_mapsuite_noImageTile = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_mapsuite_Plus = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_mapsuite_Plus_Pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int iconstyle = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int isoline = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int MapSuite = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int More = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int more40 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int settings40 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int SliderLineBackground = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int LabelStylingLayout = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int MapContainerView = 2131099671;
			
			// aapt resource value: 0x7f060014
			public const int SampleListButton = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int SettingsButton = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int TitleTextView = 2131099669;
			
			// aapt resource value: 0x7f06000d
			public const int applyButton = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int columnLinearLayour = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int columnTextView = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int conditionLinearLayour = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int conditionSpinner = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int conditionextView = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int headerLinearLayout = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int listView = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int mainLinearLayout = 2131099666;
			
			// aapt resource value: 0x7f060003
			public const int moreImageButton = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int nameTextView = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int sampleListMoreButton = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int sampleListTitle = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int settingTextView = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int settingsLinearLayout = 2131099648;
			
			// aapt resource value: 0x7f06000e
			public const int slider_view = 2131099662;
			
			// aapt resource value: 0x7f060019
			public const int uploadDataTextView = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int uploadProgressBar = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int valueEditText = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int valueLinearLayour = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int valueTextView = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBackgroundSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FilterStyleSettings = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SampleBaseLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SampleSpinnerCheckedText = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SplashLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
