#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GeometricFunctions.Resource", IsApplication=true)]

namespace GeometricFunctions
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.UI.Android.Resource.Drawable.Compass = global::GeometricFunctions.Resource.Drawable.Compass;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_globe = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Minus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Plus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.UI.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.UI.Android.Resource.String.app_name = global::GeometricFunctions.Resource.String.app_name;
			global::ThinkGeo.UI.Android.Resource.String.hello = global::GeometricFunctions.Resource.String.hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int bbox = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buffer = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int centerPoint = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int clip = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int Compass = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int convexHull = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int detail40 = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int difference = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int getArea = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int getLength = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int Icon = 2130771978;
			
			// aapt resource value: 0x7F010014
			public const int iconstyle = 2130771988;
			
			// aapt resource value: 0x7F01000B
			public const int icon_mapsuite_default256x256 = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int icon_mapsuite_default512x512 = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int icon_mapsuite_globe = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int icon_mapsuite_globe_Pressed = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int icon_mapsuite_Minus = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int icon_mapsuite_Minus_Pressed = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int icon_mapsuite_noImageTile = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int icon_mapsuite_Plus = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int icon_mapsuite_Plus_Pressed = 2130771987;
			
			// aapt resource value: 0x7F010015
			public const int lineOnLine = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int MapSuite = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int More = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int more40 = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int rotate = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int scale = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int settings40 = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int shortestLine = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int simplify = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int SliderLineBackground = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int snapGps = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int union = 2130772000;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int ExecuteButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int LabelStylingLayout = 2130837505;
			
			// aapt resource value: 0x7F020005
			public const int mainLinearLayout = 2130837509;
			
			// aapt resource value: 0x7F020002
			public const int MapContainerView = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int SampleListButton = 2130837507;
			
			// aapt resource value: 0x7F020006
			public const int sampleListMoreButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int sampleListTitle = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int sampleListView = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int slider_view = 2130837513;
			
			// aapt resource value: 0x7F020004
			public const int TitleTextView = 2130837508;
			
			// aapt resource value: 0x7F02000A
			public const int uploadDataTextView = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int uploadProgressBar = 2130837515;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int ButtonBackgroundSelector = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int SampleBaseLayout = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int SplashLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040003
			public const int hello = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
