#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GeometricFunctions.Resource", IsApplication=true)]

namespace GeometricFunctions
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::GeometricFunctions.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::GeometricFunctions.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::GeometricFunctions.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bbox = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buffer = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int centerPoint = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int clip = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Compass = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int convexHull = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int detail40 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int difference = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int getArea = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int getLength = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_mapsuite_default256x256 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_mapsuite_default512x512 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_mapsuite_globe = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_globe_Pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_mapsuite_Minus = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_mapsuite_Minus_Pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_mapsuite_noImageTile = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icon_mapsuite_Plus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon_mapsuite_Plus_Pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int iconstyle = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int lineOnLine = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int MapSuite = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int More = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int more40 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rotate = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int scale = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int settings40 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int shortestLine = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int simplify = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int SliderLineBackground = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int snapGps = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int union = 2130837536;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int ExecuteButton = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int LabelStylingLayout = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int MapContainerView = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int SampleListButton = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int TitleTextView = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int mainLinearLayout = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int sampleListMoreButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int sampleListTitle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int sampleListView = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int slider_view = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int uploadDataTextView = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int uploadProgressBar = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBackgroundSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SampleBaseLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
