#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LabelingStyle.Resource", IsApplication=true)]

namespace LabelingStyle
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.Compass = global::LabelingStyle.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default256x256 = global::LabelingStyle.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_default512x512 = global::LabelingStyle.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe = global::LabelingStyle.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_globe_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_noImageTile = global::LabelingStyle.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Android.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Plus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.Compass = global::LabelingStyle.Resource.Drawable.Compass;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default256x256 = global::LabelingStyle.Resource.Drawable.icon_mapsuite_default256x256;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_default512x512 = global::LabelingStyle.Resource.Drawable.icon_mapsuite_default512x512;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe = global::LabelingStyle.Resource.Drawable.icon_mapsuite_globe;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_globe_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_globe_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Minus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Minus_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Minus_Pressed;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_noImageTile = global::LabelingStyle.Resource.Drawable.icon_mapsuite_noImageTile;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Plus;
			global::ThinkGeo.MapSuite.Resource.Drawable.icon_mapsuite_Plus_Pressed = global::LabelingStyle.Resource.Drawable.icon_mapsuite_Plus_Pressed;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baseSettingsDialogStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int @checked = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Compass = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int CustomLabeling = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int CustomLabelingIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int detail40 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_mapsuite_default256x256 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_mapsuite_default512x512 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_mapsuite_globe = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_mapsuite_globe_Pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_mapsuite_Minus = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_mapsuite_Minus_Pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_mapsuite_noImageTile = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_mapsuite_Plus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_mapsuite_Plus_Pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int LabelingLinesIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int LabelingPoints = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int LabelingPointsIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int LabelingPolygons = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int LabelingPolygonsIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int LabelStyling = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int LabelStylingIcon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int MapSuite = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int more40 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int settings40 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int SettingsDialogBackground = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int SliderLineBackground = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int @unchecked = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int valuestyle = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001d
			public const int CancelButton = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int DuplicateRuleSpinner = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int GridSizeSpinner = 2131099662;
			
			// aapt resource value: 0x7f060016
			public const int LabelStylingLayout = 2131099670;
			
			// aapt resource value: 0x7f06001a
			public const int MapContainerView = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int MaskCheckBox = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int MaxFontSizeEditText = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int MinFontSizeEditText = 2131099650;
			
			// aapt resource value: 0x7f06001c
			public const int OkButton = 2131099676;
			
			// aapt resource value: 0x7f060009
			public const int OnlyWithinCheckBox = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int OutlineColorCheckBox = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int OverlappingCheckBox = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int PointPlacementSpinner = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int PolygonPartsCheckBox = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int SampleListButton = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int SettingsButton = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int TitleTextView = 2131099672;
			
			// aapt resource value: 0x7f060010
			public const int drawingMarginsText = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int lineSegmentRatioEditText = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06001b
			public const int mainLayout = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int mainLinearLayout = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int sampleListMoreButton = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int sampleListTitle = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int sampleListView = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int slider_view = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int splineTypeSpinner = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f06001f
			public const int uploadDataTextView = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int uploadProgressBar = 2131099678;
			
			// aapt resource value: 0x7f060007
			public const int xOffsetEditText = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int yOffsetEditText = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ButtonBackgroundSelector = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomLabelingSettingsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LabelingLinesSettingsLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LabelingPointsSettingsLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int LabelingPolygonsSettingsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LabelStylingSettingsLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SampleBaseLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SampleCheckBoxSelector = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SampleSpinnerCheckedText = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SettingsDialogBaseLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SplashLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
